improved refresh() vSp25.1

diff --git a/fn_school/refresh b/fn_school/refresh
--- a/fn_school/refresh
+++ b/fn_school/refresh
@@ -1,4 +1,5 @@
-# vim: set ft=zsh expandtab:
+# Sp25.1
+# Wed Jan 29 2025
 
 refresh() {
     for REPO in $BASE/$SEMESTYR/*/.git $BASE/emails/.git $BASE/navigation/.git; do
@@ -16,8 +17,9 @@ refresh() {
             }
 
             SHUSH=1 cd $REPO/..
-            # This Zsh construct returns 'false' when this repo has uncommitted changes
-            # The following print command prints the repo's name red in that case
+            # This Zsh construct returns 'false' when this repo has uncommitted changes,
+            # setting $? to a non-zero value.
+            # The following print command then prints the repo's name red in that case
             [[ -z $(git status --porcelain) ]]
             print -P "%f${REPO//[[:print:]]/=}\n%(?.%F{green}.%F{red})$REPO%f%b\n${REPO//[[:print:]]/=}"
 
@@ -27,34 +29,40 @@ refresh() {
                     echodo git checkout master
 
                     if ! echodo git pull publish master; then
-                        print -P "\n%F{yellow}%BPulling%b%f Notes/ from %F{green}%Bpublish%b%f failed; You must manually address this\n"
+                    print -P "\n%B%F{yellow}Pulling%f%b Notes/ from %B%F{green}publish%f%b failed; You must manually address this\n"
                         return 1
                     fi
 
                     if ! echodo git pull origin master; then
-                        print -P "\n%F{yellow}%BPulling%b%f Notes/ from %F%B{cyan}origin%b%f failed; You must manually address this\n"
+                    print -P "\n%B%F{yellow}Pulling%f%b Notes/ from %B%F{cyan}origin%f%b failed; You must manually address this\n"
                         return 1
                     fi
 
                     if ! echodo git push publish master; then
-                        print -P "\n%F{red}%BPushing%b%f Notes/ to %F{green}%Bpublish%b%f failed; You must manually address this\n"
+                    print -P "\n%B%F{red}Pushing%f%b Notes/ to %B%F{green}publish%f%b failed; You must manually address this\n"
                         return 1
                     fi
 
                     if ! echodo git push origin master; then
-                        print -P "\n%F{red}%BPushing%b%f Notes/ to %F{cyan}%Borigin%b%f failed; You must manually address this\n"
+                    print -P "\n%B%F{red}Pushing%f%b Notes/ to %B%F{cyan}origin%f%b failed; You must manually address this\n"
                         return 1
                     fi
                 )
             fi
 
+            DRYRUN=1 echodo cd $COURSEDIR
+
             # put myself back on the master branch so the pull will cleanly
             # apply if/when I'm working on a topic branch
             echodo git checkout master
-            echodo git pull --recurse-submodules=on-demand origin master
+            if ! echodo git pull --recurse-submodules=on-demand origin master; then
+                echodo git pull origin master
+            fi
             echodo git push origin master
             print
         )
     done
     ding true
 }
+
+# vim: set ft=zsh expandtab:
